# Generated by Django 5.1.6 on 2025-06-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=100)),
                ('Last_name', models.CharField(max_length=100)),
                ('Specialization', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact_number', models.CharField(max_length=15)),
                ('Availability', models.BooleanField(default=True)),
            ],
        ),
    ]
