# Generated by Django 5.1.6 on 2025-06-13 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0003_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Test_name', models.CharField(max_length=100)),
                ('Test_date', models.DateField()),
                ('Result', models.TextField()),
                ('Report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
            ],
        ),
    ]
