# Generated by Django 5.1.6 on 2025-06-13 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0004_laboratory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='Name',
        ),
        migrations.AddField(
            model_name='laboratory',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hospital.patient'),
        ),
    ]
