# Generated by Django 5.1.6 on 2025-06-18 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0006_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('cv_file', models.FileField(upload_to='cvs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='laboratory',
            old_name='Test_date',
            new_name='appointment_date',
        ),
        migrations.RenameField(
            model_name='laboratory',
            old_name='Report_file',
            new_name='report_file',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='Result',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='Test_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hospital.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratory',
            name='tests',
            field=models.ManyToManyField(to='Hospital.labtest'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
