# Generated by Django 5.1.6 on 2025-06-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0007_careerapply_labtest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='mobile',
            field=models.CharField(default='Unknown', max_length=15),
            preserve_default=False,
        ),
    ]
