# Generated by Django 5.1.6 on 2025-06-27 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0008_laboratory_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.PositiveIntegerField()),
                ('contact_phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('doctor', models.CharField(choices=[('ethel_davis', 'Dr. Ethel Davis'), ('dand_mories', 'Dr. Dand Mories'), ('dr_lee', 'Dr. Align Board')], max_length=50)),
                ('appointment_date', models.CharField(max_length=100)),
            ],
        ),
    ]
