# Generated by Django 5.1.6 on 2025-06-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0009_doctorappointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Pending', max_length=20),
        ),
    ]
