# Generated by Django 5.1.6 on 2025-06-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hospital', '0010_laboratory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapply',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='careerapply',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='careerapply',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
